### ISSUE TITLE
Update to Scala 2.11.5 and Akka 2.3.9

### ISSUE THREAD

**Issue by janekdb** [NET-A-PORTER/pre-canned#6]
It would be useful to have an update to Scala 2.11.5 and Akka 2.3.9. What is the possibility of this?

Regards,
Janek

**Comment by agustafson** [comment]
Just created PR https://github.com/NET-A-PORTER/pre-canned/pull/7 in order to address this

**Comment by theon** [comment]
This is now released as `0.0.5`.

**Comment by janekdb** [comment]
Thanks.This is working nicely for me now. The effort is appreciated.
